In [ ]:
import sqlite3
import pandas as pd
import os
from datetime import datetime

In [ ]:
conexao = sqlite3.connect(database = 'db_project_eng_dados')

In [ ]:
# Camada Bronze:
df = pd.read_csv('../landing/z0019_1.csv')
# Como já está separado por vírgulas, não há necessidade colocar esse parâmetro.
# Se o arquivo estivesse separados por ponto e vírgula, aí sim seria necessário. ()'sep = ',')

In [ ]:
df.head(2)

,id_produto,nome_produto,categoria,tipo_dado,resolucao_espacial,sistema_coordenadas,area_cobertura_km2,data_aquisicao,formato,fornecedor,preco
0,1,Mapa de Uso do Solo 2023,Mapeamento Temático,Vetorial,10m,SIRGAS 2000 / UTM 23S,1500,2023-06-15,Shapefile,GeoMapas Ltda,3500.0
1,2,Modelo Digital de Elevação,MDE,Raster,30m,WGS84,5000,2022-11-20,GeoTIFF,INPE,0.0

In [ ]:
# Dicionário de dados:
# Pode salvar como: dicionario_bronze_produtos.csv
# Ótimo para documentação do projeto ou README

In [ ]:
arquivo = 'z0019_1.csv'
data_ingestion = datetime.now()
df['data_bronze'] = data_ingestion
df.head(2)

,id_produto,nome_produto,categoria,tipo_dado,resolucao_espacial,sistema_coordenadas,area_cobertura_km2,data_aquisicao,formato,fornecedor,preco,data_bronze
0,1,Mapa de Uso do Solo 2023,Mapeamento Temático,Vetorial,10m,SIRGAS 2000 / UTM 23S,1500,2023-06-15,Shapefile,GeoMapas Ltda,3500.0,2025-12-21 22:59:59.577108
1,2,Modelo Digital de Elevação,MDE,Raster,30m,WGS84,5000,2022-11-20,GeoTIFF,INPE,0.0,2025-12-21 22:59:59.577108

In [ ]:
conexao.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos(
                id_produto TEXT, 
                nome_produto TEXT,
                categoria TEXT,
                tipo_dado TEXT,
                resolucao_espacial REAL,
                sistema_coordenadas TEXT,
                area_cobertura_km2 REAL,
                data_aquisicao TEXT,
                formato TEXT,
                fornecedor TEXT,
                preco REAL,
                data_bronze TEXT) """)